version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: ghcr.io/berdjds/testing-docker-backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://testuser:testpass@mysql:3306/testdb
      JWT_SECRET: your_jwt_secret
      FRONTEND_URL: http://localhost
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: ghcr.io/berdjds/testing-docker-frontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost/api
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
